<?php
define('APPLICATION_PATH', realpath(dirname(__FILE__) . '/'));
define('TWITTER_API_KEY', "");
define('TWITTER_API_KEY_SECRET', "");
define('TWITTER_ACCESS_TOKEN', "");
define('TWITTER_ACCESS_TOKEN_SECRET', "");
define('FACEBOOK_APP_ID', 517793025693665);
define('FACEBOOK_PAGE_ID', 109412767101979);
define('FACEBOOK_APP_SECRET', "");
define('FACEBOOK_ACC_TOKEN', "");
define('TYNYMCE_API_KEY', '');
define('ABSOLUTE_PATH', "https://www.geopole.net");
define('IS_DEV', true);
define('LOGO_SVG_PATH', ABSOLUTE_PATH . "/res/images/svg/logo.svg");
define('LOGO_PNG_PATH', ABSOLUTE_PATH . "/res/images/svg/logo.png");
define('LOGO_AMP_PATH', ABSOLUTE_PATH . "/res/images/amp-logo.png");
define('MYSQL_HOST', "mysql-lucasnonime.alwaysdata.net");
define('MYSQL_DB', "lucasnonime_blogdb");
define('MYSQL_USER', "169783");
define('MYSQL_PASS', "root");
